### ISSUE TITLE
data import fails with 'No data to import. Is the chosen format correct?'

### ISSUE THREAD

**Issue by ICHydro** [ImperialCollegeLondon/paricia#332]
**Describe the bug**
Data import fails with 'No data to import. Is the chosen format correct?' The data format seems correct, however when clicking on the data file, the website generates an error "Not Found. The requested resource was not found on this server."

**To Reproduce**
1. Import a data file
2. Click on the data file name after importing (see screenshot)
3. Observe "Not found error"

**Expected behavior**
Data file should be available after importing

**Screenshots**
![Screenshot 2024-09-20 011450](https://github.com/user-attachments/assets/b30ad740-1e73-40f7-8447-d1f735042fe1)

**Additional context**
It is not clear whether this is really a problem with the data format, or somehow the system does not find the uploaded file.

**Comment by dalonsoa** [comment]
There are two problems here:
1. Error message indicating that the upload failed. This might be for a number of reasons, and I agree that the message is not very informative. Even if the `format` object is correct, it might not have any variable associated with it. For that you need to create a [`Classification`](https://imperialcollegelondon.github.io/paricia/Applications/formatting/#formatting.models.Classification), linking one or more variables with a format. That you have this problem points to a need for more clear error messages and a more detailed _HowTo_ in the documentation for uploading data.
2. The file cannot be downloaded because Django in production, by default, prevents from downloading raw data files for security reasons. They need to be served in a different way. If downloading the raw data files is a thing, I'll create an issue about that.

**Comment by dalonsoa** [comment]
To be addressed in:
- #333 
- #334

**Comment by ICHydro** [comment]
Data import works fine after generating a classification
