### ISSUE TITLE
Present time information to the user in the relevant timezone

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/paricia#375]
Some times (like the submission time) should be presented to the user in the user's timezone, but others (like the data being ingested, or the plots in the dash apps) should be presented to the user in the original timezone the data belongs to. At the moment, everything is presented in UTC, which is the default timezone of the app, as indicated in the settings. This is confusing. More information, in https://docs.djangoproject.com/en/5.1/topics/i18n/timezones/

_Originally posted by @dalonsoa in https://github.com/ImperialCollegeLondon/paricia/issues/364#issuecomment-2392847297_

**Comment by dalonsoa** [comment]
It seems that this is way, way more complicated than anticipated. Data is correctly ingested in the DB using the timezone of the Station it belongs to, and stored internally in UTC. The problem comes when displaying the data in the original timezone and, more over, if there're times that we want to be displayed in the original timezone and others in the user's timezone.

For the information displayed in the Admin, there's no much we can do without severe hacking. For the custom views and the reporting and validation views, there might be some options, but need more investigation.

**Comment by dalonsoa** [comment]
@ICHydro in what timezone do you want the users to see datetime information? At the moment, everything is displayed in UTC.

**Comment by ICHydro** [comment]
On the short term I think that we can default to always displaying data in the user's timezone. This is what other systems such as Thingsboard seem to do. On the longer term, we would probably still default to this behaviour, but add a functionality such as a button "display data in the sensor's timezone" that allows switching between both for certain custom views.

As an intermediate option, we may also consider displaying a warning if the station time zone and the users time zone differ, to make them alert to this.

I have not read the Django doc in detail, but I suppose that there is a way to infer the users timezone from their browsing information? This would be needed for anonymous users, and is probably also the best way to do things for most logged in users. We may consider an option that registered users set a specific time zone in their settings, but I would make this optional because it may be confusing if they set it and then forget they've set it.

Would that simplify things? In any case, most users will be based in the same time zone as their stations.

**Comment by dalonsoa** [comment]
All sounds good. Local timezone seems to be reasonable. It is not possible to infer timezone based on browser info - [see the docs](https://docs.djangoproject.com/en/5.1/topics/i18n/timezones/#selecting-the-current-time-zone) - but we can easily implement either a selector to store the information in the user's profile - if logged - or try to [infer things from the IP](https://github.com/Miserlou/django-easy-timezones) if not logged. 

In any case, it is clear - let's work on user's local timezone.
